package com.salesforce.zsync4j;

import java.io.IOException;

/**
 * Indicates that the output file generated by zsync is not valid 
 *
 * @author bbusjaeger
 *
 */
public class OutputFileValidationException extends IOException {

  private static final long serialVersionUID = 6774699463758923383L;

  public OutputFileValidationException(String message, Throwable cause) {
    super(message, cause);
  }

  public OutputFileValidationException(String message) {
    super(message);
  }

}
