package com.salesforce.zsync4j;


/**
 * Indicates that the output file generated by zsync is not valid
 *
 * @author bbusjaeger
 *
 */
public class ZsyncChecksumValidationFailedException extends ZsyncException {

  private static final long serialVersionUID = 6774699463758923383L;

  public ZsyncChecksumValidationFailedException(String message, Throwable cause) {
    super(message, cause);
  }

  public ZsyncChecksumValidationFailedException(String message) {
    super(message);
  }

}
